routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
 */
Route::auth();
Route::get('/logout', 'Auth\LoginController@logout');
Route::group(['middleware' => ['auth']], function () {

    /**
     * Main
     */
    Route::get('/', 'PagesController@dashboard');
    Route::get('dashboard', 'PagesController@dashboard')->name('dashboard');

    /**
     * Users
     */
    Route::group(['prefix' => 'users'], function () {
        Route::get('/data', 'UsersController@anyData')->name('users.data');
        Route::get('/taskdata/{id}', 'UsersController@taskData')->name('users.taskdata');
        Route::get('/leaddata/{id}', 'UsersController@leadData')->name('users.leaddata');
        Route::get('/clientdata/{id}', 'UsersController@clientData')->name('users.clientdata');
        Route::get('/users', 'UsersController@users')->name('users.userdata');
    });
    Route::resource('users', 'UsersController');

    /**
     * Roles
     */
    Route::resource('roles', 'RolesController');
    /**
     * Clients
     */
    Route::group(['prefix' => 'clients'], function () {
        Route::get('/data', 'ClientsController@anyData')->name('clients.data');
        Route::get('/excel', 'ClientsController@excel')->name('clients.excel');
        Route::post('/importExcel', 'ClientsController@importExcel')->name('clients.importExcel');
        Route::post('/create/cvrapi', 'ClientsController@cvrapiStart');
        Route::post('/upload/{id}', 'DocumentsController@upload');
        Route::patch('/updateassign/{id}', 'ClientsController@updateAssign');
    });
    Route::resource('clients', 'ClientsController');
    Route::resource('documents', 'DocumentsController');


    /**
     * Tasks
     */
    Route::group(['prefix' => 'tasks'], function () {
        Route::get('/data', 'TasksController@anyData')->name('tasks.data');
        Route::patch('/updatestatus/{id}', 'TasksController@updateStatus');
        Route::patch('/updateassign/{id}', 'TasksController@updateAssign');
        Route::post('/updatetime/{id}', 'TasksController@updateTime');
    });
    Route::resource('tasks', 'TasksController');

    /**
     * Leads
     */
    Route::group(['prefix' => 'leads'], function () {
        Route::get('/data', 'LeadsController@anyData')->name('leads.data');
        Route::patch('/updateassign/{id}', 'LeadsController@updateAssign');
        Route::patch('/updatestatus/{id}', 'LeadsController@updateStatus');
        Route::patch('/updatefollowup/{id}', 'LeadsController@updateFollowup')->name('leads.followup');
    });
    Route::resource('leads', 'LeadsController');
    Route::post('/comments/{type}/{id}', 'CommentController@store');
    /**
     * Settings
     */
    Route::group(['prefix' => 'settings'], function () {
        Route::get('/', 'SettingsController@index')->name('settings.index');
        Route::patch('/permissionsUpdate', 'SettingsController@permissionsUpdate');
        Route::patch('/overall', 'SettingsController@updateOverall');
    });

    /**
     * Departments
     */
    Route::resource('departments', 'DepartmentsController');

    /**
     * Integrations
     */
    Route::group(['prefix' => 'integrations'], function () {
        Route::get('Integration/slack', 'IntegrationsController@slack');
    });
    Route::resource('integrations', 'IntegrationsController');

    /**
     * Notifications
     */
    Route::group(['prefix' => 'notifications'], function () {
        Route::post('/markread', 'NotificationsController@markRead')->name('notification.read');
        Route::get('/markall', 'NotificationsController@markAll');
        Route::get('/{id}', 'NotificationsController@markRead');
    });

    /**
     * Invoices
     */
    Route::group(['prefix' => 'invoices'], function () {
        Route::post('/updatepayment/{id}', 'InvoicesController@updatePayment')->name('invoice.payment.date');
        Route::post('/reopenpayment/{id}', 'InvoicesController@reopenPayment')->name('invoice.payment.reopen');
        Route::post('/sentinvoice/{id}', 'InvoicesController@updateSentStatus')->name('invoice.sent');
        Route::post('/newitem/{id}', 'InvoicesController@newItem')->name('invoice.new.item');
    });
    Route::resource('invoices', 'InvoicesController');
});

app/Models/Client.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{

    protected $fillable = [
        'name',
        'company_name',
        'vat',
        'email',
        'address',
        'zipcode',
        'city',
        'primary_number',
        'secondary_number',
        'industry_id',
        'company_type',
        'user_id'];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function industry()
    {
        return $this->belongsTo(Industry::class);
    }

   public function tasks()
    {
        return $this->hasMany(Task::class, 'client_id', 'id')
            ->orderBy('status', 'asc')
            ->orderBy('created_at', 'desc');
    }

    public function leads()
    {
        return $this->hasMany(Lead::class, 'client_id', 'id')
            ->orderBy('status', 'asc')
            ->orderBy('created_at', 'desc');
    }

    public function documents()
    {
        return $this->hasMany(Document::class, 'client_id', 'id');
    }

    public function invoices()
    {
        return $this->hasMany(Invoice::class);
    }

    public function getAssignedUserAttribute()
    {
        return User::findOrFail($this->user_id);
    }
}

app/Models/Lead.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon;

class Lead extends Model
{
    protected $fillable = [
        'title',
        'description',
        'status',
        'user_assigned_id',
        'user_created_id',
        'client_id',
        'contact_date',

    ];
    protected $dates = ['contact_date'];

    protected $hidden = ['remember_token'];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_assigned_id');
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'user_created_id');
    }

    public function client()
    {
        return $this->belongsTo(Client::class, 'client_id');
    }

    public function comments()
    {
        return $this->morphMany(Comment::class, 'source');
    }

    public function activity()
    {
        return $this->morphMany(Activity::class, 'source');
    }

    public function getDaysUntilContactAttribute()
    {
        return Carbon\Carbon::now()->startOfDay()->diffInDays($this->contact_date, false);
    }

    /**
     * Add a reply to the thread.
     *
     * @param  array $reply
     * @return Model
     */
    public function addComment($reply)
    {
        $reply = $this->comments()->create($reply);
        return $reply;
    }
}

app/Models/Task.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon;

class Task extends Model
{

    protected $fillable = [
        'title',
        'description',
        'status',
        'user_assigned_id',
        'user_created_id',
        'client_id',
        'deadline'
    ];
    protected $dates = ['deadline'];

    protected $hidden = ['remember_token'];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_assigned_id');
    }

    public function invoice(){
        return $this->belongsTo(Invoice::class);
    }

    public function client()
    {
        return $this->belongsTo(Client::class, 'client_id');
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'user_created_id');
    }

    public function comments()
    {
        return $this->morphMany(Comment::class, 'source');
    }

    public function getDaysUntilDeadlineAttribute()
    {
        return Carbon\Carbon::now()
            ->startOfDay()
            ->diffInDays($this->deadline, false); // if you are past your deadline, the value returned will be negative.

    }

    public function getAssignedUserAttribute()
    {
        return User::findOrFail($this->user_assigned_id);
    }

    public function getCreatorUserAttribute()
    {
        return User::findOrFail($this->user_assigned_id);
    }

    public function activity()
    {
        return $this->morphMany(Activity::class, 'source');
    }

    public function canUpdateInvoice(){
        //If there is no invoice, it should be possible, because it also creates
        if(!$this->invoice)
        {
            return true;
        }
        return $this->invoice->canUpdateInvoice();
    }

    /**
     * Add a reply to the thread.
     *
     * @param  array $reply
     * @return Model
     */
    public function addComment($reply)
    {
        $reply = $this->comments()->create($reply);
        return $reply;
    }
}

app/Http/Controllers/ClientsController.php
<?php
namespace App\Http\Controllers;

use Config;
use Dinero;
use Datatables;
use App\Models\Client;
use App\Http\Requests;
use Illuminate\Http\Request;
use App\Http\Requests\Client\StoreClientRequest;
use App\Http\Requests\Client\UpdateClientRequest;
use App\Repositories\User\UserRepositoryContract;
use App\Repositories\Client\ClientRepositoryContract;
use App\Repositories\Setting\SettingRepositoryContract;
use Excel;

class ClientsController extends Controller
{

    protected $users;
    protected $clients;
    protected $settings;

    public function __construct(
        UserRepositoryContract $users,
        ClientRepositoryContract $clients,
        SettingRepositoryContract $settings
    ) {
    
        $this->users = $users;
        $this->clients = $clients;
        $this->settings = $settings;
        $this->middleware('client.create', ['only' => ['create']]);
        $this->middleware('client.update', ['only' => ['edit']]);
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('clients.index');
    }

    /**
     * Make json respnse for datatables
     * @return mixed
     */
    public function anyData()
    {
        $clients = Client::select(['id', 'name', 'company_name', 'email', 'primary_number']);
        return Datatables::of($clients)
            ->addColumn('namelink', function ($clients) {
                return '<a href="clients/' . $clients->id . '" ">' . $clients->name . '</a>';
            })
            ->add_column('edit', '
                <a href="{{ route(\'clients.edit\', $id) }}" class="btn btn-success" >Edit</a>')
            ->add_column('delete', '
                <form action="{{ route(\'clients.destroy\', $id) }}" method="POST">
            <input type="hidden" name="_method" value="DELETE">
            <input type="submit" name="submit" value="Delete" class="btn btn-danger" onClick="return confirm(\'Are you sure?\')"">

            {{csrf_field()}}
            </form>')
            ->make(true);
    }

    public function excel()
    {
        $clients = Client::all();
        $arr =array();
        $header=array('ID', 'Name', 'Email', 'Primary Number', 'Secondary Number', 'Address', 'Zip Code', 'City', 'Company Name', 'VAT', 'Company Type', 'User Assigned', 'Industry', 'Created At', 'Updated At');
        array_push($arr, $header);
        foreach ($clients as $client) {
            $industry = '';
            if ($client->industry != null || $client->industry == '') {
                $industry = ' ';
            } else {
                $industry = $client->industry->name;
            }
            $data=array(
                $client->id,
                $client->name,
                $client->email,
                $client->primary_number,
                $client->secondary_number,
                $client->address,
                $client->zipcode,
                $client->city,
                $client->company_name,
                $client->vat,
                $client->company_type,
                $client->user->name,
                $industry,
                $client->created_at,
                $client->updated_at,
            );
            array_push($arr, $data);
        }
        // dd($arr);
        Excel::create('clients', function ($excel) use ($arr) {
            $excel->setTitle('Clients');
            $excel->setCreator('BIT')->setCompany('UEH BIT');
            $excel->setDescription('Clients list');
    
            $excel->sheet('sheet1', function ($sheet) use ($arr) {
                $sheet->fromArray($arr, null, 'A1', false, false);
                $sheet->freezeFirstRow();
                $sheet->freezeFirstColumn();
                $sheet->cells('A1:O1', function ($cells) {
                    $cells->setFontWeight('bold');
                    $cells->setBackground('#F2C40F');
                });
            });
        })->download('xlsx');
    }

    public function importExcel(Request $request)
    {
        $this->validate($request, [
            'file' => 'mimes:xlsx'
        ]);
        if ($request->hasFile('file')) {
            $path = $request->file('file')->getRealPath();
            $data = Excel::load($path, function ($reader) {
            })->get();
        }
        $insert = [];
        if (!empty($data) && $data->count()) {
            foreach ($data as $key => $value) {
                $assignee_name = \App\Models\User::where('name', $value->user_assigned)->first();
                if ($assignee_name != null) {
                    $assignee_id=$assignee_name->id;
                } else {
                    $assignee_id = 1;
                }

                $industry_name=\App\Models\Industry::where('name', $value->industry)->first();
                if ($industry_name != null) {
                    $industry_id = $industry_name->id;
                } else {
                    $industry_id = 1;
                }
                
                $insert[] = [
                    'id' => $value->id,
                    'name' => $value->name,
                    'email' => $value->email,
                    'primary_number' => $value->primary_number,
                    'secondary_number' => $value->secondary_number,
                    'address' => $value->address,
                    'zipcode' => $value->zip_code,
                    'city' => $value->city,
                    'company_name' => $value->company_name,
                    'vat' => $value->vat,
                    'company_type' => $value->company_type,
                    'user_id' => $assignee_id,
                    'industry_id' => $industry_id,
                    'created_at' => $value->created_at,
                    'updated_at' => $value->updated_at
                ];
            }
            
            if (!empty($insert)) {
                \Illuminate\Support\Facades\DB::table('clients')->insert($insert);
            } else {
                Session()->flash('flash_message_warning', 'Cannot import excel file');
            }
        }
        return back();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return mixed
     */
    public function create()
    {
        return view('clients.create')
            ->withUsers($this->users->getAllUsersWithDepartments())
            ->withIndustries($this->clients->listAllIndustries());
    }

    /**
     * @param StoreClientRequest $request
     * @return mixed
     */
    public function store(StoreClientRequest $request)
    {
        $this->clients->create($request->all());
        return redirect()->route('clients.index');
    }

    /**
     * @param Request $vatRequest
     * @return mixed
     */
    public function cvrapiStart(Request $vatRequest)
    {
        return redirect()->back()
            ->with('data', $this->clients->vat($vatRequest));
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return mixed
     */
    public function show($id)
    {
        return view('clients.show')
            ->withClient($this->clients->find($id))
            ->withCompanyname($this->settings->getCompanyName())
            ->withInvoices($this->clients->getInvoices($id))
            ->withUsers($this->users->getAllUsersWithDepartments());
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return mixed
     */
    public function edit($id)
    {
        return view('clients.edit')
            ->withClient($this->clients->find($id))
            ->withUsers($this->users->getAllUsersWithDepartments())
            ->withIndustries($this->clients->listAllIndustries());
    }

    /**
     * @param $id
     * @param UpdateClientRequest $request
     * @return mixed
     */
    public function update($id, UpdateClientRequest $request)
    {
        $this->clients->update($id, $request);
        Session()->flash('flash_message', 'Client successfully updated');
        return redirect()->route('clients.index');
    }

    /**
     * @param $id
     * @return mixed
     */
    public function destroy($id)
    {
        $this->clients->destroy($id);

        return redirect()->route('clients.index');
    }

    /**
     * @param $id
     * @param Request $request
     * @return mixed
     */
    public function updateAssign($id, Request $request)
    {
        $this->clients->updateAssign($id, $request);
        Session()->flash('flash_message', 'New user is assigned');
        return redirect()->back();
    }
}

resources/views/clients/tabs/documenttab.blade.php
<div id="document" class="tab-pane fade">
    <table class="table">
        <h4>{{ __('All Documents') }}</h4>
        <div class="col-xs-10">
            <div class="form-group">
                <form method="POST" action="{{ url('/clients/upload', $client->id)}}" class="dropzone" id="dropzone"
                      files="true" data-dz-removea
                      enctype="multipart/form-data"
                >
                    <meta name="csrf-token" content="{{ csrf_token() }}">
                </form>
                <p><b>{{ __('Max size') }}</b></p>
            </div>
        </div>
        <thead>
        <tr>
            <th>{{ __('File') }}</th>
            <th>{{ __('Size') }}</th>
            <th>{{ __('Created at') }}</th>
        </tr>
        </thead>
        <tbody>
        @foreach($client->documents as $document)
            <tr>
                <td><a href="../files/{{$companyname}}/{{$document->path}}"
                       target="_blank">{{$document->file_display}}</a></td>
                <td>{{$document->size}} <span class="moveright"> MB</span></td>
                <td>{{$document->created_at}}</td>
		
                <td>
		<form method="POST" action="{{action('DocumentsController@destroy', $document->id)}}">
		<input type="hidden" name="_method" value="delete"/>
		<input type="hidden" name="_token" value="{{csrf_token()}}"/>
		<input type="submit" class="btn btn-danger" value="Delete"/>
		</form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

</div>

resources/views/clients/tabs/invoicetab.blade.php
<div id="invoice" class="tab-pane fade">
    <div class="boxspace">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>{{ __('ID') }}</th>
                <th>{{ __('Hours') }}</th>
                <th>{{ __('Totalt amount') }}</th>
                <th>{{ __('Invoice sent') }}</th>
                <th>{{ __('Payment received') }}</th>
                <th>{{ __('Status') }}</th>
            </tr>
            </thead>
            <tbody>
            <?php $total = 0; ?>
            @foreach($invoices as $invoice)
                <tr>
                    <td>
                        <a href="{{route('invoices.show', $invoice->id)}}">
                            {{$invoice->id}}
                        </a>
                    </td>
                    <td>
                        <?php $total = 0; ?>
                        @foreach($invoice->invoiceLines as $invoiceLine)
                            <?php $total += $invoiceLine->quantity; ?>

                        @endforeach
                        {{$total}}
                    </td>
                    <td>
                        <?php $totalAmount = 0; ?>
                        @foreach($invoice->invoiceLines as $payment)
                            <?php $totalAmount += $payment->price; ?>
                        @endforeach
                        {{$totalAmount}},-
                    </td>
                    <td>
                        @if($invoice->sent_at == null)
                            <?php $color = "red"; ?>
                        @else
                            <?php $color = "green"; ?>
                        @endif
                        <p style=" color:{{$color}}">{{$invoice->sent_at ? 'yes' : 'no'}}</p>
                    </td>
                    <td>
                        @if($invoice->payment_received_at == null)
                            <?php $color = "red"; ?>
                        @else
                            <?php $color = "green"; ?>
                        @endif
                        <p style=" color:{{$color}}">{{$invoice->payment_received_at ? 'yes' : 'no'}}</p>

                    </td>
                    <td>
                        <p>{{$invoice->status}}</p>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>

resources/views/clients/tabs/leadtab.blade.php
<div id="lead" class="tab-pane fade">
    <div class="boxspace">
        <table class="table table-hover">
            <h4>{{ __('All Leads') }}</h4>
            <thead>
            <thead>
            <tr>
                <th>{{ __('Title') }}</th>
                <th>{{ __('Assigned user') }}</th>
                <th>{{ __('Created at') }}</th>
                <th>{{ __('Deadline') }}</th>

                <th><a href="{{ route('leads.create', ['client' => $client->id])}}">
                        <button class="btn btn-success">{{ __('New Lead') }}</button>
                    </a></th>

            </tr>
            </thead>
            <tbody>
            <?php  $tr = ""; ?>
          
            @foreach($client->leads as $lead)
                @if($lead->status == 1)
                    <?php  $tr = '#adebad'; ?>
                @elseif($lead->status == 2)
                    <?php $tr = '#ff6666'; ?>
                @endif
                <tr style="background-color:<?php echo $tr;?>">

                    <td><a href="{{ route('leads.show', $lead->id) }}">{{$lead->title}} </a></td>
                    <td>
                        <div class="popoverOption"
                             rel="popover"
                             data-placement="left"
                             data-html="true"
                             data-original-title="<span class='glyphicon glyphicon-user' aria-hidden='true'> </span> {{$lead->user->name}}">
                            <div id="popover_content_wrapper" style="display:none; width:250px;">
                                <img src='http://placehold.it/350x150' height='80px' width='80px'
                                     style="float:left; margin-bottom:5px;"/>
                                <p class="popovertext">
                                    <span class="glyphicon glyphicon-envelope" aria-hidden="true"> </span>
                                    <a href="mailto:{{$lead->user->email}}">
                                        {{$lead->user->email}}<br/>
                                    </a>
                                    <span class="glyphicon glyphicon-headphones" aria-hidden="true"> </span>
                                    <a href="mailto:{{$lead->user->work_number}}">
                                    {{$lead->user->work_number}}</p>
                                </a>

                            </div>
                            <a href="{{route('users.show', $lead->user->id)}}"> {{$lead->user->name}}</a>

                        </div> <!--Shows users assigned to lead -->
                    </td>
                    <td>{{date('d, M Y, H:i', strTotime($lead->cotact_date))}}  </td>
                    <td>{{date('d, M Y', strTotime($lead->contact_date))}}
                        @if($lead->status == 1)({{ $lead->days_until_contact }})@endif </td>
                    <td></td>
                </tr>

            @endforeach

            </tbody>
        </table>
    </div>
</div>

resources/views/clients/tabs/tasktab.blade.php
<div id="task" class="tab-pane fade in active">
    <div class="boxspace">
        <table class="table table-hover">
            <h4>{{ __('All Tasks') }}</h4>
            <thead>
            <thead>
            <tr>
                <th>{{ __('Title') }}</th>
                <th>{{ __('Assigned') }}</th>
                <th>{{ __('Created at') }}</th>
                <th>{{ __('Deadline') }}</th>
                <th><a href="{{ route('tasks.create', ['client' => $client->id])}}">
                        <button class="btn btn-success">{{ __('New task') }}</button>
                    </a></th>

            </tr>
            </thead>
            <tbody>
            <?php  $tr = ""; ?>
            @foreach($client->tasks as $task)
                @if($task->status == 1)
                    <?php  $tr = '#adebad'; ?>
                @elseif($task->status == 2)
                    <?php $tr = '#ff6666'; ?>
                @endif
                <tr style="background-color:<?php echo $tr;?>">

                    <td><a href="{{ route('tasks.show', $task->id) }}">{{$task->title}} </a></td>
                    <td>
                        <div class="popoverOption"
                             rel="popover"
                             data-placement="left"
                             data-html="true"
                             data-original-title="<span class='glyphicon glyphicon-user' aria-hidden='true'> </span> {{$task->user->name}}">
                            <div id="popover_content_wrapper" style="display:none; width:250px;">
                                <img src='http://placehold.it/350x150' height='80px' width='80px'
                                     style="float:left; margin-bottom:5px;"/>
                                <p class="popovertext">
                                    <span class="glyphicon glyphicon-envelope" aria-hidden="true"> </span>
                                    <a href="mailto:{{$task->user->email}}">
                                        {{$task->user->email}}<br/>
                                    </a>
                                    <span class="glyphicon glyphicon-headphones" aria-hidden="true"> </span>
                                    <a href="mailto:{{$task->user->work_number}}">
                                    {{$task->user->work_number}}</p>
                                </a>

                            </div>
                            <a href="{{route('users.show', $task->user->id)}}"> {{$task->user->name}}</a>

                        </div> <!--Shows users assigned to task -->
                    </td>
                    <td>{{date('d, M Y, H:i', strTotime($task->created_at))}}  </td>
                    <td>{{date('d, M Y', strTotime($task->deadline))}}
                        @if($task->status == 1)({{ $task->days_until_deadline }}) @endif</td>
                    <td></td>
                </tr>

            @endforeach

            </tbody>
        </table>
    </div>